### ISSUE TITLE
Removal of `plugin-compat`

### ISSUE THREAD

**Issue by ghost** [acolorbright/eslint-config-acb-base#7]
🚨 PSA: NEW BRANCH

New branch with `eslint-plugin-compat` removed
- It's called: `eslint-config-acb-base/no-plugin-compat` 🙂 
- Same branch is added to `eslint-config-acb` with dependence on `eslint-config-acb-base/no-pluginp-compat`

*Reasoning*
Due to inability to override plugins (e.g. disabling them completely) from apps that depended on `eslint-config-acb-base` and the fact that `babel0env` causes `eslint-plugin-compat` to lose its value.

> Since we are using `babel-env` in some projects its interaction with `eslint-plugin-compat` is confusing
E.g. it is throwing an error that `Object.value()` is not supported in IE11;
At the same time all unsupported things will be polyfilled by `babel-env` for very same browsers `eslint-plugin-compat` is testing against @ (since they share `browserlist` config).

*Future steps*
`eslint-plugin-compat` (branch merged) should be removed completely and projects are advised to rely on `babel-env`

**Comment by heldinz** [comment]
Closed via ba01547ff7b35597cbe92df8c0cced152ad4d96e
